#+TITLE:	Code Review
#+AUTHOR:	Jan Meppe

* What is this 
This document describes /what/ code review is, /why/ it is important,
and /what/ steps organisations can take to implement code review in
their organisations.

The intended audience for this document are tech-savvy people
without a proper software engineering background (like myself) but
whom are *eager to learn* and implement best practices. 

This document is a living document and subject to change. 
* What is code review 

#+BEGIN_QUOTE
"Code Review, or Peer Code Review, is the act of consciously and
systematically convening with one’s fellow programmers to check each
other’s code for mistakes."

---Smartbear.com [1] 
#+END_QUOTE

* Why is code review important 
Code review is important. To stress this importance let me open up with a quote from the founder of StackOverflow: 
#+BEGIN_QUOTE
"I believe that peer code reviews are the single biggest thing you can
do to improve your code."

---Jeff Atwood (founder of StackOverflow) 
#+END_QUOTE
Here's another quote from Steve McConnell
#+BEGIN_QUOTE
"Individual inspections typically catch about 60% of all bugs/defects,
which is more than any other technique."

---Steve McConnell (author of Code Complete)
#+END_QUOTE

* Sources 
[1] https://smartbear.com/learn/code-review/what-is-code-review/

* Other notes 
- `<q<TAB>` to insert a quote
- TODO: Figure out how to do [1] references in org-mode 




